name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.14.1'
      - name: Make script executable
        run: chmod +x ./.github/workflows/run-gradle-in-directories.sh
      - name: Run exercises in chapter 1
        run: |
          CHAPTER="exercise-files/chapter_1"
          TASKS="$CHAPTER/01_02-end=build $CHAPTER/01_03-start=build $CHAPTER/01_03-end=build $CHAPTER/01_04-start=build $CHAPTER/01_04-end=build $CHAPTER/01_05-start=build $CHAPTER/01_05-end=build $CHAPTER/01_06-start=build $CHAPTER/01_06-end=build"
      - name: Run exercises in chapter 2
        run: |
          CHAPTER="exercise-files/chapter_2"
          TASKS="$CHAPTER/02_02-end=build $CHAPTER/02_03-start=build $CHAPTER/02_03-end=build $CHAPTER/02_04-start=build $CHAPTER/02_04-end=build $CHAPTER/02_05-start=build $CHAPTER/02_05-end=build $CHAPTER/02_06-start=build $CHAPTER/02_06-end=build"
          ./.github/workflows/run-gradle-in-directories.sh "$TASKS"
      - name: Run exercises in chapter 3
        run: |
          CHAPTER="exercise-files/chapter_3"
          TASKS="$CHAPTER/03_02-end=build $CHAPTER/03_03-end=build $CHAPTER/03_04-end=build"
          ./.github/workflows/run-gradle-in-directories.sh "$TASKS"